# TEMPORARY FILE FOR TRIVY TESTING ONLY
# Remove/revert this before merging.

FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y curl vim netcat-openbsd openssl

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py /app/app.py

RUN chmod -R 777 /app

EXPOSE 22
EXPOSE 80

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]